"""
ProgressionSystem: manages game level progression, waves, and boss triggers.
Uses the Game instance for canvas/entity operations to avoid behavior changes.
"""
from typing import Any
from constants import (
    GAME_LEVEL_WAVES,
    LEVEL_REST_DURATION,
    MAX_ENEMY_COUNT,
    WAVE_SPAWN_INTERVAL,
    ENEMY_SIZE,
    ENEMY_SIZE_HALF,
)
from entities import BossEnemy


class ProgressionSystem:
    def __init__(self, game: Any):
        self.game = game

    def start_game_level(self) -> None:
        # Boss level (moved to level 10)
        if self.game.game_level == 10:
            self.start_boss_fight()
            return
        # Reset wave/rest timers
        self.game.current_wave = 0
        self.game.wave_timer = 0
        self.game.is_resting = False
        self.game.level_rest_timer = 0
        # Spawn first wave
        self.spawn_next_wave()

    def spawn_next_wave(self) -> None:
        # If level beyond defined, use autogen
        if self.game.game_level not in GAME_LEVEL_WAVES:
            self.spawn_next_wave_autogenerated()
            return
        waves = GAME_LEVEL_WAVES[self.game.game_level]
        # Completed all waves → rest period
        if self.game.current_wave >= len(waves):
            print(
                f"[LEVEL COMPLETE] Level {self.game.game_level} - all {len(waves)} waves completed, entering rest period"
            )
            self.game.is_resting = True
            self.game.level_rest_timer = LEVEL_REST_DURATION
            return
        # Spawn specified wave
        enemy_type, count, spawn_delay = waves[self.game.current_wave]
        print(
            f"[WAVE SPAWN] Level {self.game.game_level}, Wave {self.game.current_wave + 1}: Spawning {count} {enemy_type} enemies (total enemies: {len(self.game.enemies)})"
        )
        available_slots = MAX_ENEMY_COUNT - len(self.game.enemies)
        actual_count = min(count, available_slots)
        if actual_count < count:
            print(
                f"[WAVE SPAWN] Capped spawn at {actual_count}/{count} enemies due to MAX_ENEMY_COUNT ({MAX_ENEMY_COUNT})"
            )
        for _ in range(actual_count):
            x, y = self.game._get_spawn_position()
            self.game._spawn_enemy_by_type(x, y, enemy_type)
        self.game.current_wave += 1
        self.game.wave_timer = WAVE_SPAWN_INTERVAL
        print(
            f"[WAVE SPAWN] Wave spawned. Total enemies now: {len(self.game.enemies)}, next wave in 5s"
        )

    def spawn_next_wave_autogenerated(self) -> None:
        # Autogenerated difficulty beyond level 20
        num_waves = min(6 + (self.game.game_level // 10), 10)
        num_waves_per_level = max(6, num_waves - self.game.current_wave)
        if self.game.current_wave >= num_waves_per_level:
            self.game.is_resting = True
            self.game.level_rest_timer = LEVEL_REST_DURATION
            return
        total_enemies = 15 + (self.game.game_level - 20) * 2
        pentagon_ratio = min(0.5, 0.02 * (self.game.game_level - 20) + 0.1)
        triangle_ratio = min(0.7, 0.3 + (0.02 * (self.game.game_level - 20)))
        pentagons = int(total_enemies * pentagon_ratio)
        triangles = int(total_enemies * triangle_ratio * (1 - pentagon_ratio))
        basics = total_enemies - pentagons - triangles
        available_slots = MAX_ENEMY_COUNT - len(self.game.enemies)
        actual_total = min(total_enemies, available_slots)
        if actual_total < total_enemies:
            scale = actual_total / total_enemies
            basics = int(basics * scale)
            triangles = int(triangles * scale)
            pentagons = int(pentagons * scale)
            print(
                f"[WAVE SPAWN] Scaled autogen spawn to {actual_total}/{total_enemies} enemies due to MAX_ENEMY_COUNT"
            )
        for _ in range(basics):
            x, y = self.game._get_spawn_position()
            self.game._spawn_enemy_by_type(x, y, 'square')
        for _ in range(triangles):
            x, y = self.game._get_spawn_position()
            self.game._spawn_enemy_by_type(x, y, 'triangle')
        for _ in range(pentagons):
            x, y = self.game._get_spawn_position()
            self.game._spawn_enemy_by_type(x, y, 'pentagon')
        self.game.current_wave += 1
        self.game.wave_timer = WAVE_SPAWN_INTERVAL

    def start_boss_fight(self) -> None:
        print("[BOSS] ===== BOSS FIGHT INITIATED =====")
        self.game.boss_fight_active = True
        self.game.boss_announcement_timer = 3000
        self.game.boss_minion_spawn_timer = 5000
        boss_x = self.game.window_width // 2 - ENEMY_SIZE // 2
        boss_y = self.game.window_height // 2 - ENEMY_SIZE // 2
        self.game.current_boss = BossEnemy(self.game.canvas, boss_x, boss_y, ENEMY_SIZE)
        self.game.enemies.append(self.game.current_boss)
        # Clear existing enemies for clean boss fight
        for enemy in self.game.enemies[:-1]:
            try:
                self.game.canvas.delete(enemy.rect)
            except Exception:
                pass
        self.game.enemies = [self.game.current_boss]
        print(f"[BOSS] Boss spawned with {self.game.current_boss.health} HP")

    def tick(self) -> None:
        """Advance progression timers by one logic tick (20ms)."""
        # Handle rest period between levels
        if self.game.is_resting:
            if len(self.game.enemies) == 0:
                self.game.level_rest_timer -= 20
                if self.game.level_rest_timer <= 0:
                    self.game.is_resting = False
                    self.game.game_level += 1
                    self.start_game_level()
            return
        # Decrement wave timer and spawn when expired
        self.game.wave_timer -= 20
        if self.game.wave_timer <= 0:
            self.spawn_next_wave()
